spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: 1998
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:8088"
  main:
    allow-circular-references: true
#eureka:
#  client:
#    enabled: true

feign:
  client:
    config:
      SapService:
        readTimeout: 5000
        connectTimeout: 5000

#server:
#  forward-headers-strategy: framework