#server:
#  port: 8060
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8061/eureka/
#
#zuul:
#  routes:
#    student-service:
#      path: /api/student/**
#      serviceId: student-service
#    group-service:
#      path: /api/group/**
#      serviceId: group-service
#    auth-service:
#      path: /api/open-auth/auth/**
#      serviceId: auth-service

#ribbon:
#  eureka:
#    enabled: false