spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: postgres
  application:
    name: student-service
  config:
    import: "optional:configserver:http://localhost:8088"

service:

  productServiceUsername: product
  productServicePassword: product123

  authServiceUsername: auth
  authServicePassword: auth123

  gatewayServiceUsername: gateway
  gatewayServicePassword: gateway123

serviceUsername : serviceUsername
servicePassword : servicePassword