server:
  port: 9080

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: postgres
  application:
    name: student-service
  config:
    import: "optional:configserver:http://localhost:8088"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


service:
  studentServiceUsername: student
  studentServicePassword: student123

serviceUsername : serviceUsername
servicePassword : servicePassword

feign:
  client:
    config:
      SapService:
        readTimeout: 5000
        connectTimeout: 5000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

springdoc:
  packagesToScan: uz.uzcard.services.student.controller


