spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: postgres
  application:
    name: student-service
  config:
    import: "optional:configserver:http://localhost:8088"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


service:
  studentServiceUsername: student
  studentServicePassword: student123

#  authServiceUsername: auth
#  authServicePassword: auth123
#
#  gatewayServiceUsername: gateway
#  gatewayServicePassword: gateway123

serviceUsername : serviceUsername
servicePassword : servicePassword

#eureka:
#  client:
#    enabled: true

feign:
  client:
    config:
      SapService:
        readTimeout: 5000
        connectTimeout: 5000
