spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: 1998
  application:
    name: student-service
  config:
    import: "optional:configserver:http://localhost:8088"