server:
  port: 8061

spring:
  application:
    name: registry-service
  config:
    import: "optional:configserver:http://localhost:8088"

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/