server:
  port: 9081

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: postgres
  application:
    name: group-service
  config:
    import: "optional:configserver:http://localhost:8088"

service:
  groupServiceUsername: group
  groupServicePassword: group123

serviceUsername: serviceUsername
servicePassword: servicePassword

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

springdoc:
  packagesToScan: uz.uzcard.services.group.controller